### ISSUE TITLE
error : don't know the reason

### ISSUE THREAD

**Issue by XiangNanLi** [chemzqm/mockapi#1]
... Starting Livereload server on 35729
server listening on 4000
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1057:14)

**Comment by chemzqm** [comment]
Redis 服务找不到啊

**Comment by XiangNanLi** [comment]
可是redis我重新安装了也是一样的

发自我的 iPhone

**Comment by chemzqm** [comment]
服务没起来 执行 redis-cli 看下吧，你要把 redis 服务设置成自动启动
